#!/bin/bash
# Script to reorganize the DNA_GAN_Project directory

# Create new simplified directory structure
mkdir -p dna_gan_web/data
mkdir -p dna_gan_web/models
mkdir -p dna_gan_web/static/images
mkdir -p dna_gan_web/static/css
mkdir -p dna_gan_web/static/js
mkdir -p dna_gan_web/templates
mkdir -p dna_gan_web/utils

# Copy essential data files
cp data/preprocessed_dna_sequences.fasta dna_gan_web/data/ 2>/dev/null
cp data/gumbel_generated_sequences.fasta dna_gan_web/data/ 2>/dev/null
cp data/improved_generated_sequences.fasta dna_gan_web/data/ 2>/dev/null

# Copy model files
cp models/gumbel_softmax_gan/*.py dna_gan_web/models/ 2>/dev/null
cp models/improved_wgan/*.py dna_gan_web/models/ 2>/dev/null

# Copy utility files
cp utils/preprocess_with_random_replacement.py dna_gan_web/utils/ 2>/dev/null
cp utils/check_cuda.py dna_gan_web/utils/ 2>/dev/null
cp utils/generate_test_sequences.py dna_gan_web/utils/ 2>/dev/null

# Copy evaluation metrics
mkdir -p dna_gan_web/evaluation/metrics
cp evaluation/metrics/*.py dna_gan_web/evaluation/metrics/ 2>/dev/null
cp evaluation/evaluate_sequences.py dna_gan_web/evaluation/ 2>/dev/null

# Copy visualization files
cp visualization/streamlit_app_comparison.py dna_gan_web/templates/app.py 2>/dev/null
cp visualization/streamlit_evaluation_page.py dna_gan_web/templates/evaluation_page.py 2>/dev/null

# Copy checkpoints
mkdir -p dna_gan_web/checkpoints/gumbel_softmax_gan
mkdir -p dna_gan_web/checkpoints/improved_wgan
cp checkpoints/gumbel_softmax_gan/*.pt dna_gan_web/checkpoints/gumbel_softmax_gan/ 2>/dev/null
cp checkpoints/improved_wgan/*.pt dna_gan_web/checkpoints/improved_wgan/ 2>/dev/null

# Create simplified run scripts
echo '#!/bin/bash' > dna_gan_web/run_app.sh
echo 'python -m streamlit run templates/app.py' >> dna_gan_web/run_app.sh
chmod +x dna_gan_web/run_app.sh

echo '@echo off' > dna_gan_web/run_app.bat
echo 'python -m streamlit run templates\app.py' >> dna_gan_web/run_app.bat

# Create README file
cat > dna_gan_web/README.md << 'EOF'
# DNA GAN Web Interface

This web interface allows you to:

1. View original DNA sequences
2. View sequences generated by Gumbel-Softmax GAN
3. View sequences generated by Wasserstein GAN
4. Compare and analyze all three datasets

## Running the App

```bash
# On Windows
run_app.bat

# On Unix/MacOS
chmod +x run_app.sh
./run_app.sh
```
EOF

echo "Reorganization completed. The simplified directory structure is now in the 'dna_gan_web' folder."
