@echo off
REM Script to reorganize the DNA_GAN_Project directory

REM Create new simplified directory structure
mkdir dna_gan_web 2>nul
mkdir dna_gan_web\data 2>nul
mkdir dna_gan_web\models 2>nul
mkdir dna_gan_web\static 2>nul
mkdir dna_gan_web\static\images 2>nul
mkdir dna_gan_web\static\css 2>nul
mkdir dna_gan_web\static\js 2>nul
mkdir dna_gan_web\templates 2>nul
mkdir dna_gan_web\utils 2>nul

REM Copy essential data files
copy data\preprocessed_dna_sequences.fasta dna_gan_web\data\ 2>nul
copy data\gumbel_generated_sequences.fasta dna_gan_web\data\ 2>nul
copy data\improved_generated_sequences.fasta dna_gan_web\data\ 2>nul

REM Copy model files
copy models\gumbel_softmax_gan\*.py dna_gan_web\models\ 2>nul
copy models\improved_wgan\*.py dna_gan_web\models\ 2>nul

REM Copy utility files
copy utils\preprocess_with_random_replacement.py dna_gan_web\utils\ 2>nul
copy utils\check_cuda.py dna_gan_web\utils\ 2>nul
copy utils\generate_test_sequences.py dna_gan_web\utils\ 2>nul

REM Copy evaluation metrics
mkdir dna_gan_web\evaluation 2>nul
mkdir dna_gan_web\evaluation\metrics 2>nul
copy evaluation\metrics\*.py dna_gan_web\evaluation\metrics\ 2>nul
copy evaluation\evaluate_sequences.py dna_gan_web\evaluation\ 2>nul

REM Copy visualization files
copy visualization\streamlit_app_comparison.py dna_gan_web\templates\app.py 2>nul
copy visualization\streamlit_evaluation_page.py dna_gan_web\templates\evaluation_page.py 2>nul

REM Copy checkpoints
mkdir dna_gan_web\checkpoints 2>nul
mkdir dna_gan_web\checkpoints\gumbel_softmax_gan 2>nul
mkdir dna_gan_web\checkpoints\improved_wgan 2>nul
copy checkpoints\gumbel_softmax_gan\*.pt dna_gan_web\checkpoints\gumbel_softmax_gan\ 2>nul
copy checkpoints\improved_wgan\*.pt dna_gan_web\checkpoints\improved_wgan\ 2>nul

REM Create simplified run scripts
echo @echo off > dna_gan_web\run_app.bat
echo python -m streamlit run templates\app.py >> dna_gan_web\run_app.bat

echo #!/bin/bash > dna_gan_web\run_app.sh
echo python -m streamlit run templates/app.py >> dna_gan_web\run_app.sh

REM Create README file
echo # DNA GAN Web Interface > dna_gan_web\README.md
echo. >> dna_gan_web\README.md
echo This web interface allows you to: >> dna_gan_web\README.md
echo. >> dna_gan_web\README.md
echo 1. View original DNA sequences >> dna_gan_web\README.md
echo 2. View sequences generated by Gumbel-Softmax GAN >> dna_gan_web\README.md
echo 3. View sequences generated by Wasserstein GAN >> dna_gan_web\README.md
echo 4. Compare and analyze all three datasets >> dna_gan_web\README.md
echo. >> dna_gan_web\README.md
echo ## Running the App >> dna_gan_web\README.md
echo. >> dna_gan_web\README.md
echo ```bash >> dna_gan_web\README.md
echo # On Windows >> dna_gan_web\README.md
echo run_app.bat >> dna_gan_web\README.md
echo. >> dna_gan_web\README.md
echo # On Unix/MacOS >> dna_gan_web\README.md
echo chmod +x run_app.sh >> dna_gan_web\README.md
echo ./run_app.sh >> dna_gan_web\README.md
echo ``` >> dna_gan_web\README.md

echo Reorganization completed. The simplified directory structure is now in the 'dna_gan_web' folder.
